name: bamboo_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  device_info_plus: ^11.2.0
  excel: ^4.0.6
  file_picker: ^8.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  go_router: ^14.2.7
  flutter_map: ^6.1.0                                          
  latlong2: ^0.9.0
  image_picker: ^1.1.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  supabase_flutter: ^2.8.2
  uuid: ^4.5.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  # Offline Storage & Sync
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  connectivity_plus: ^5.0.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # Drift code generation
  drift_dev: ^2.15.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/.env
    - assets/images/Logo_Sapuran_Berperan.png
    - assets/dark_mode_map.json
    - assets/images/SiMandja-Logo.png
